### PR TITLE
Fix log config location

### LINKED ISSUE #134: log config should be written to log directory regardless of whether or not the default logger is used
@petecheslock indicates that we have shipped a regression with regard to log configs:
https://twitter.com/petecheslock/status/612715767595945984

The changes from #82 seem to have gone missing; I can't tell from commit log when they would have merged to develop. We included #117 in the 1.7.0 release, but that change doesn't resolve the problem for configurations which do not use the `default_logger`.

### PR DESCRIPTION
**Pull request by cwjohnston**
Closes #134

### CODE REVIEW

**Comment by yyuu** [comment]
What is the current status of this?

File: test/integration/service/serverspec/debian_spec.rb [hunk 1]
```diff
@@ -43,6 +43,10 @@
         it { should be_grouped_into 'root' }
       end
 
+      describe file('/etc/service/plain-defaults/log/config') do
```
Comment (yyuu) [inline test/integration/service/serverspec/debian_spec.rb]: If I understand correctly, svlogd's configuration file should be put into log directory like '/etc/service/plain-defaults/lig/main/config'. It should not be at the same level with log's run script.

Comment (cwjohnston) [inline test/integration/service/serverspec/debian_spec.rb]: Thanks for pointing this out. I think it's okay for the config file to live in the same directory as the log's run script, as long as we also symlink it into the directory where the log process will write to. I'll update the PR to ensure that linking occurs.
