### PR TITLE
Move log config file from log service dir into log dir

### LINKED ISSUE #69: svlogd configuration in wrong place?
When I use the `runit_service` in my cookbook like this:

```
runit_service "nutcracker" do
  action [ :enable, :start ]
  run_template_name 'nutcracker'
  default_logger    true
  log_size           50000000
  cookbook          'nutcracker'
end
```

It creates the svlogd configuration under `/etc/sv/nutcracker/log/config`, but the svlogd reads configuration from `/var/log/nutcracker/config` (the default dir created by the `default_logger true`).

The manpage for svlogd says about its configuration file location:

> A log directory additionally contains the lock file lock, maybe state and newstate, and  optionally the file _config_.  svlogd creates necessary files if they don't exist.

_In practice_, the config file created by the runit_service resource is useless unless the write directory is the same as the sv control directory (by default `/etc/sv/<service>`).

Is this the desired behavior? And if it is, what is the best practice to make the config file go to the right place using the `runit_service` resource instead of putting a template on the write logs directory?

System: Debian GNU/Linux 7.5 (wheezy)
Runit Version: 2.1.1-6.2
Chef Version: 11.12.4-1
Cookbook Version: 1.5.8

### PR DESCRIPTION
**Pull request by mkropat**
This PR is an alternate implementation of #47 (the difference being this PR includes tests). It would fix #69 and #75.

The core issue being addressed is that the all the `log_*` parameters offered by the recipe do not work.  The recipe places the `config` file in the log service directory, but the `config` needs to go into the actual log directory. The `svlogd` documentation [is clear about this](http://smarden.org/runit/svlogd.8.html):

> On startup [...] **svlogd** checks for each log directory *log* if the configuration file *log/config* exists, and if so, reads the file line by line [...]

In addition, this PR adds a new recipe parameter, `log_dir`, which lets the user override the default log directory path.

### CODE REVIEW

File: test/spec/libraries/resource_runit_service_spec.rb [hunk 1]
```diff
@@ -272,6 +272,15 @@
     resource.sv_verbose.should eq(true)
   end
 
+  it 'has a log_dir parameter that defaults to "/var/log/service_name"' do
+    resource.log_dir.should eq(::File.join('/var/log', resource.service_name))
```
Comment (jtimberman) [inline test/spec/libraries/resource_runit_service_spec.rb]: I think this should be:

```ruby
resource.log_dir.should eq('/var/log/getty.service')
```

I know we're using `resource.service_name` in other places in this spec, but since we set it, we know what it will be and should ensure that we're testing the right thing.

**Comment by jtimberman** [comment]
As long as all the tests are passing I think this looks good. Thank you for making an effort to keep backwards compatibility too :smile_cat: :cake:

**Comment by mkropat** [comment]
I just noticed that there are integration test instructions (`bundle exec kitchen test`). I can't test that right now as my host machine is running Windows. I will test it tonight on my Linux box.
